#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

if test $(git diff --cached -z HEAD | grep -E "[+]\s+[A-Z_]+SECRET_(ID|KEY): ?\w+" | wc -c) != 0
then
	cat <<\EOF
Error: 你他妈忘记把密码删了, 啥b.
EOF
	exit 1
fi
