# "1": "巴哈姆特@夜喵貓貓咪喵(asaz5566a)",
# "2": "bilbilibili@朝夕desu(4607471)",
# "3": "bilbilibili@y千代(49533273)",
# "4": "bilbilibili@蔚蓝档案(3493265644980448)",
# "5": "bilbilibili@白夜清露(35434465)",
# "6": "bilbilibili@本心Official(20612969)",
# "7": "bilbilibili@赛博夜猫攻略组-白夜清露(20612969)",
# "8": "bilbilibili@碧蓝档案资讯站(37507923)",
image:
  - name: 'test'
    path: './image/some/'
    url: ''
    group: ''
    type: "vertical" # horizen or vertical
    source: '7'
  - name: 'test'
    path: './image/some/'
    url: ''
    source: '7'
  - name: 'test'
    path: './image/student_rank/'
    url: ''
    source: '7'