# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: AutoUploadReleaseBuild

on:
  push:
    tags:
      - 'v*'
jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./arona-core
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        #更改工作目录
      - name: Navigate to subdirectory
        run: |
          cd $GITHUB_WORKSPACE/arona-core
          ls -la
        #安装使用jdk
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
        #执行构建
      - name: Build with Gradle 7.2
        uses: gradle/gradle-build-action@v3.3.2
        with:
          arguments: :buildPlugin
        #取文件名
      - name: Get Plugin Name
        run: echo "NAME=$(find build/mirai -name "*.jar" -exec basename {} \;)" >> $GITHUB_ENV
        #上传工件
      - name: Upload-Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NAME }}
          path: build/mirai/${{ env.NAME }}

      #自动发布
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/mirai/${{ env.NAME }}"
          prerelease: ${{ contains(github.ref, 'pre') }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
      - name: Success
        id: success
        run: echo "::set-output name=should_continue::true"
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
