# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: AutoUploadReleaseBuild

on:
  push:
    tags:
      - 'v*'
jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./arona-core
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        #安装使用jdk
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        #下载并安装指定版本的 Gradle
      - name: Install Gradle 7.2
        run: |
          wget https://services.gradle.org/distributions/gradle-7.2-bin.zip -P /tmp
          unzip -d /opt/gradle /tmp/gradle-7.2-bin.zip
          echo "/opt/gradle/gradle-7.2/bin" >> $GITHUB_PATH
        #执行构建
      - name: Build with Gradle 7.2
        working-directory: ./arona-core
        run: gradle buildPlugin  # 注意这里直接使用 gradle 命令

#      - name: Build with Gradle 7.2
#        uses: gradle/gradle-build-action@v3.3.2
#        working-directory: ./arona-core
#        with:
#          arguments: :buildPlugin
#

        #取文件名
      - name: Get Plugin Name
        run: echo "NAME=$(find arona-core/build/mirai -name "*.jar" -exec basename {} \;)" >> $GITHUB_ENV
          echo find arona-core/build/mirai -name "*.jar" -exec basename {} \;
        #上传工件
      - name: Upload-Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NAME }}
          path: build/mirai/${{ env.NAME }}

      #自动发布
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "arona-core/build/mirai/${{ env.NAME }}"
          prerelease: ${{ contains(github.ref, 'pre') }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
      - name: Success
        id: success
        run: echo "::set-output name=should_continue::true"
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
#  dependency-submission:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
#      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
#      - name: Generate and submit dependency graph
#        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
